### ISSUE TITLE
Create new sketch fails for ESP8266 with version 4

### ISSUE THREAD

**Issue by Harry4Offies** [Sloeber/arduino-eclipse-plugin#1090]
**Describe the bug**
Installed latest V4.3.1_win64.2018-10-10_08-21-58.tar.gz. 
Creation of a new ESP8266 sketch failed after a few seconds with

**To Reproduce**
1. Go to Arduino Creat new Sketch and click on it
2. Configure like screenshot
![Sketchsettings](https://user-images.githubusercontent.com/50888015/58129321-cb660c00-7c19-11e9-8f9f-708369b27cb1.JPG)

3. Wait a few seconds
4. See error (sreen shot and logging)
![ErrorScreen](https://user-images.githubusercontent.com/50888015/58129386-e9337100-7c19-11e9-8f60-2a21c8954834.JPG)
[Logging.txt](https://github.com/Sloeber/arduino-eclipse-plugin/files/3204441/Logging.txt)

**Expected behavior**
A simple empty sketch to be created

**Desktop (please complete the following information):**
 - OS: Windows 10
 - N.A.
 - N.A.

**Comment by jonnieZG** [comment]
Same here. I have tested with WEMOS D1 R2 mini and several others, but the same problem persist when I try to use 2.5.1 or 2.5.2. I'd say it's a Java version problem related to the Regex Pattern resolution.

![image](https://user-images.githubusercontent.com/8830300/58457708-a137b100-8127-11e9-8814-d508b4c9db74.png)

And here's the entire log of the event. Just rewind to its start and you'll see a StackOverflowError caused due to an internal Java regex Pattern resolution error. I've seen it happen before on several occasions in other Java apps, so my solution was to rephrase a problematic regex pattern.

[log.zip](https://github.com/Sloeber/arduino-eclipse-plugin/files/3226048/log.zip)

**Comment by smartmicrodevel** [comment]
Same issue here, would love to use 2.5.2!
Any workaround?

**Comment by jonnieZG** [comment]
> Same issue here, would love to use 2.5.2!
> Any workaround?

I couldn't find any, so I'm stuck on 2.5.0.

**Comment by BbIKTOP** [comment]
"Latest" nightly build works ok but does not compile due to some empty parameters it tries to pass to the esptool.py. Tried to modify ExternalCommandLauncher constructor that does String#split with regex, but cannot build it. So I changed esptool.py to eliminatine empty args:
```
import sys
import os


i=0
while(i<len(sys.argv)):
    if str(sys.argv[i])=='':
        sys.argv.pop(i)
    else:
        i=i+1

sys.argv.pop(0) # Remove executable name
```

But looks like nobody maintains Sloeber now. It's sad. Probably it's time to move to the PlatformIO (

**Comment by smartmicrodevel** [comment]
> > Same issue here, would love to use 2.5.2!
> > Any workaround?
> 
> I couldn't find any, so I'm stuck on 2.5.0.

Tried increasing stack size of JVM via -Xss512m but even that won't help. What happend to the guys who maintained this?

**Comment by jonnieZG** [comment]
> Tried increasing stack size of JVM via -Xss512m but even that won't help.
There is a recursive loop that Regex parser falls into. Increasing memory won't help, the Regex has to be rephrased.

> What happend to the guys who maintained this?
I guess that Life is what happened. ;) Maintaining an open source is OK when you are young and you don't have any other worries, but later on in life all these things fall down on your list of priorities, especially if they don't pay, even more if they require additional investments on your behalf.

**Comment by tvand** [comment]
I tried to debug the problem. It is in /io.sloeber.core/src/io/sloeber/core/tools/Helpers.java#setTheEnvironmentVariablesPostProcessing()

The problem happens when variables are used twice in a recipe. I will try to provide a patch but meanwhile you may work around the problem by changing 
`tools.esptool.upload.pattern="{cmd}" "{runtime.platform.path}/tools/upload.py" --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" {upload.erase_cmd} --end --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" write_flash 0x0 "{build.path}/{build.project_name}.bin" --end`

to

`tools.esptool.upload.pattern="{cmd}" "{runtime.platform.path}/tools/upload.py" --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" "{upload.verbose}" {upload.erase_cmd} --end --chip esp8266 --port "{serial.port}" --baud "{upload.speed}" write_flash 0x0 "{build.path}/{build.project_name}.bin" --end`

in platform.txt.

**Comment by tvand** [comment]
> I guess that Life is what happened. ;) Maintaining an open source is OK when you are young and you don't have any other worries, but later on in life all these things fall down on your list of priorities, especially if they don't pay, even more if they require additional investments on your behalf.

The latest activity in the repository was the removal of requests for donations. Go figure.

**Comment by tvand** [comment]
Fixed in #1073

**Comment by jonnieZG** [comment]
Ok, seems to be working now. 

1. Go to Window >> Preferences >> Install/Update >> Available Software Sites and add this location (you can name it Sloeber Nightly or whatever you like) **http://eclipse.baeyens.it/update/V4/nightly/**
2. Help >> Check for Updates
3. Select **only** **Sloeber** and **Sloeber Plugin** and install that.

Should be working fine when done.

**Comment by amirna2** [comment]
Still failing on Mac OSX using latest Eclipse CDT Version: 2019-06 (4.12.0) and the latest nightly plugin build version 4.3.1.201902260606.
Used the steps above: https://github.com/Sloeber/arduino-eclipse-plugin/issues/1090#issuecomment-504675603

**Comment by erdemuncuoglu** [comment]
Hi @amirna2
Your issue has a solution. Check my comment in #1102.
